
/* NOTE: This file is auto-generated from authors.xml, do not edit it. */

static const gchar * const authors[] =
{
  "Spencer Kimball",
  "Peter Mattis",
  "Nicola Archibald",
  "Luis Barrancos",
  "Hans Breuer",
  "Simon Budig",
  "João S. O. Bueno",
  "Lars-Peter Clausen",
  "Kevin Cozens",
  "Michael Deal",
  "Alexia Death",
  "Daniel Eddeland",
  "Ulf-D. Ehlert",
  "Saul Goode",
  "David Gowers",
  "Marcus Heese",
  "Daniel Hornung",
  "Barak Itkin",
  "Róman Joost",
  "Geert Jordaens",
  "Aurimas Juška",
  "Øyvind Kolås",
  "Tom Lechner",
  "Tor Lillqvist",
  "Luidnel Maignan",
  "John Marshall",
  "Michael Natterer",
  "Sven Neumann",
  "Martin Nordholts",
  "Ville Pätsi",
  "Mikael Magnusson",
  "Christian Krippendorf",
  "Nils Philippsen",
  "Raphaël Quinet",
  "Dennis Ranke",
  "Michael Schumacher",
  "Peter Sikking",
  "Jernej Simončič",
  "Manish Singh",
  "William Skaggs",
  "Jakub Steiner",
  NULL
};

static const gchar * const artists[] =
{
  "Alexia Death",
  "Aurore Derriennic",
  "Ville Pätsi",
  "Jakub Steiner",
  NULL
};

static const gchar * const documenters[] =
{
  "Ignacio AntI",
  "Žygimantas Beručka",
  "Marco Ciampa",
  "Dust",
  "Ulf-D. Ehlert",
  "Alessandro Falappa",
  "Julien Hardelin",
  "Róman Joost",
  "Jean-Pierre Litzler",
  "Vitaly Lomov",
  "Pierre Perrier",
  "Baurzhan Muftakhidinov",
  "Joe Hansen",
  "Carles Ferrando",
  "Pedro Barreira",
  "Francisco Vila",
  "Xandru Armesto",
  "Gitte Illum Petersen",
  "Dimitris Spingos",
  "Sergio Cipolla",
  "Rudolfs Mazurs",
  "Kristjan SCHMIDT",
  "Piotr Drąg",
  "Fran Dieguez",
  "Nishibori Kiyotaka",
  "Muhammet Kara",
  "Alexandre Prokoudine",
  "Patrycja Stawiarska",
  "Kolbjørn Stuestøl",
  "Axel Wernicke",
  NULL
};
